[env:RV32IM]
# act-config: rve-rv32im
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_M=1

[env:RV32IA]
# act-config: rve-rv32ia
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_A=1

[env:RV32IC]
# act-config: rve-rv32ic
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1

[env:RV32IB]
# act-config: rve-rv32ib
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_B=1

[env:RV32IZaamo]
# act-config: rve-rv32izaamo
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZAAMO=1

[env:RV32IZalrsc]
# act-config: rve-rv32izalrsc
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZALRSC=1

[env:RV32IZmmul]
# act-config: rve-rv32izmmul
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZMMUL=1

[env:RV32IZicsr]
# act-config: rve-rv32izicsr
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZICSR=1

[env:RV32IZifencei]
# act-config: rve-rv32izifencei
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZIFENCEI=1

[env:RV32IZba]
# act-config: rve-rv32izba
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZBA=1

[env:RV32IZbb]
# act-config: rve-rv32izbb
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZBB=1

[env:RV32IZbc]
# act-config: rve-rv32izbc
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZBC=1

[env:RV32IZbs]
# act-config: rve-rv32izbs
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZBS=1

[env:RV32IACBZmmul_Zicsr_Zifencei]
# act-config: rve-rv32iacbzmmul_zicsr_zifencei
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_A=1
  -D RVE_E_C=1
  -D RVE_E_B=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1

[env:RV32IACZmmul_Zicsr_Zifencei_Zba_Zbb_Zbc_Zbs]
# act-config: rve-rv32iaczmmul_zicsr_zifencei_zba_zbb_zbc_zbs
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_A=1
  -D RVE_E_C=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZBS=1

[env:RV32ICBZaamo_Zalrsc_Zmmul_Zicsr_Zifencei]
# act-config: rve-rv32icbzaamo_zalrsc_zmmul_zicsr_zifencei
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1
  -D RVE_E_B=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1

[env:RV32ICBZaamo_Zalrsc_Zmmul_Zifencei]
# act-config: rve-rv32icbzaamo_zalrsc_zmmul_zifencei
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1
  -D RVE_E_B=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZIFENCEI=1

[env:RV32ICBZaamo_Zmmul_Zicsr]
# act-config: rve-rv32icbzaamo_zmmul_zicsr
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1
  -D RVE_E_B=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZICSR=1

[env:RV32ICZaamo_Zalrsc_Zmmul_Zicsr_Zifencei_Zba_Zbb_Zbc_Zbs]
# act-config: rve-rv32iczaamo_zalrsc_zmmul_zicsr_zifencei_zba_zbb_zbc_zbs
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZBS=1

[env:RV32IMABZicsr_Zifencei]
# act-config: rve-rv32imabzicsr_zifencei
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_M=1
  -D RVE_E_A=1
  -D RVE_E_B=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1

[env:RV32IMACBZicsr_Zifencei]
# act-config: rve-rv32imacbzicsr_zifencei
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_M=1
  -D RVE_E_A=1
  -D RVE_E_C=1
  -D RVE_E_B=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1

[env:RV32IMACZicsr_Zba_Zbb_Zbc_Zbs]
# act-config: rve-rv32imaczicsr_zba_zbb_zbc_zbs
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_M=1
  -D RVE_E_A=1
  -D RVE_E_C=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZBS=1

[env:RV32IMACZifencei_Zba_Zbb_Zbc_Zbs]
# act-config: rve-rv32imaczifencei_zba_zbb_zbc_zbs
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_M=1
  -D RVE_E_A=1
  -D RVE_E_C=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZBS=1

[env:RV32IMBZaamo_Zalrsc_Zicsr_Zifencei]
# act-config: rve-rv32imbzaamo_zalrsc_zicsr_zifencei
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_M=1
  -D RVE_E_B=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1

[env:RV32IMCBZaamo_Zalrsc_Zicsr_Zifencei]
# act-config: rve-rv32imcbzaamo_zalrsc_zicsr_zifencei
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_M=1
  -D RVE_E_C=1
  -D RVE_E_B=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1

[env:RV32IMCZaamo_Zalrsc_Zicsr_Zifencei_Zba_Zbb_Zbc_Zbs]
# act-config: rve-rv32imczaamo_zalrsc_zicsr_zifencei_zba_zbb_zbc_zbs
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_M=1
  -D RVE_E_C=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZBS=1

[env:RV32IZifencei_Zbb]
# act-config: rve-rv32izifencei_zbb
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBB=1

