[env:RV32I]
# act-config: rve-rv32i
# smoke
extends           = common
build_flags       =
  ${common.build_flags}

[env:RV32IM]
# act-config: rve-rv32im
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_M=1

[env:RV32IA]
# act-config: rve-rv32ia
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_A=1

[env:RV32IC]
# act-config: rve-rv32ic
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1

[env:RV32IB]
# act-config: rve-rv32ib
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_B=1

[env:RV32IZaamo]
# act-config: rve-rv32izaamo
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZAAMO=1

[env:RV32IZalrsc]
# act-config: rve-rv32izalrsc
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZALRSC=1

[env:RV32IZmmul]
# act-config: rve-rv32izmmul
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZMMUL=1

[env:RV32IZicsr]
# act-config: rve-rv32izicsr
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZICSR=1

[env:RV32IZifencei]
# act-config: rve-rv32izifencei
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZIFENCEI=1

[env:RV32IZba]
# act-config: rve-rv32izba
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZBA=1

[env:RV32IZbb]
# act-config: rve-rv32izbb
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZBB=1

[env:RV32IZbc]
# act-config: rve-rv32izbc
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZBC=1

[env:RV32IZbkc]
# act-config: rve-rv32izbkc
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZBKC=1

[env:RV32IZbkb]
# act-config: rve-rv32izbkb
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZBKB=1

[env:RV32IZbkx]
# act-config: rve-rv32izbkx
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZBKX=1

[env:RV32IZbs]
# act-config: rve-rv32izbs
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZBS=1

[env:RV32ICZcb]
# act-config: rve-rv32iczcb
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1
  -D RVE_E_ZCB=1

[env:RV32ICZcmop]
# act-config: rve-rv32iczcmop
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1
  -D RVE_E_ZCMOP=1

[env:RV32IZicntr_Zicsr]
# act-config: rve-rv32izicntr_zicsr
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZICSR=1

[env:RV32IZicond]
# act-config: rve-rv32izicond
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZICOND=1

[env:RV32IZihintntl]
# act-config: rve-rv32izihintntl
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZIHINTNTL=1

[env:RV32IZihintpause]
# act-config: rve-rv32izihintpause
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZIHINTPAUSE=1

[env:RV32IZimop]
# act-config: rve-rv32izimop
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZIMOP=1

[env:RV32IMisalign]
# act-config: rve-rv32imisalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_MISALIGNED=1

[env:RV32IAZba_Zicond_Misalign_MCZicsr_Zifencei_Zbb_Zbkc_Zcb_Zcmop_Zihintntl_Zihintpause]
# act-config: rve-rv32iazba_zicond_misalign_mczicsr_zifencei_zbb_zbkc_zcb_zcmop_zihintntl_zihintpause
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_A=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZICOND=1
  -D RVE_E_MISALIGNED=1
  -D RVE_E_M=1
  -D RVE_E_C=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBKC=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZIHINTPAUSE=1

[env:RV32IAZicsr_Zifencei_Zimop_CBZmmul_Zcb_Zcmop_Zicntr_Zicond_Zihintntl_Zihintpause_Misalign]
# act-config: rve-rv32iazicsr_zifencei_zimop_cbzmmul_zcb_zcmop_zicntr_zicond_zihintntl_zihintpause_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_A=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZIMOP=1
  -D RVE_E_C=1
  -D RVE_E_B=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_MISALIGNED=1

[env:RV32IAZmmul_Zbkb_Zihintpause_CZicsr_Zifencei_Zbb_Zbc_Zbkx_Zcb_Zcmop_Zicntr_Zicond_Zimop_Misalign]
# act-config: rve-rv32iazmmul_zbkb_zihintpause_czicsr_zifencei_zbb_zbc_zbkx_zcb_zcmop_zicntr_zicond_zimop_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_A=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZBKB=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_C=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIMOP=1
  -D RVE_E_MISALIGNED=1

[env:RV32IAZmmul_Zbs_Zicond_CZicsr_Zifencei_Zba_Zbb_Zbc_Zbkb_Zbkx_Zcb_Zicntr_Zihintntl_Zimop]
# act-config: rve-rv32iazmmul_zbs_zicond_czicsr_zifencei_zba_zbb_zbc_zbkb_zbkx_zcb_zicntr_zihintntl_zimop
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_A=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZBS=1
  -D RVE_E_ZICOND=1
  -D RVE_E_C=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZBKB=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZIMOP=1

[env:RV32ICZalrsc_Zcmop_Misalign_BZaamo_Zmmul_Zicsr_Zifencei_Zicntr_Zicond_Zihintntl_Zihintpause_Zimop]
# act-config: rve-rv32iczalrsc_zcmop_misalign_bzaamo_zmmul_zicsr_zifencei_zicntr_zicond_zihintntl_zihintpause_zimop
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_MISALIGNED=1
  -D RVE_E_B=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_ZIMOP=1

[env:RV32ICZbb_Zbkc_Zbkb_AZmmul_Zifencei_Zba_Zbkx_Zbs_Zcb_Zcmop_Zicond_Zihintntl_Zihintpause_Zimop_Misalign]
# act-config: rve-rv32iczbb_zbkc_zbkb_azmmul_zifencei_zba_zbkx_zbs_zcb_zcmop_zicond_zihintntl_zihintpause_zimop_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBKC=1
  -D RVE_E_ZBKB=1
  -D RVE_E_A=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZBS=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_ZIMOP=1
  -D RVE_E_MISALIGNED=1

[env:RV32ICZbs_Zcmop_Zihintpause_MAZicsr_Zba_Zbb_Zbc_Zcb_Zihintntl_Zimop_Misalign]
# act-config: rve-rv32iczbs_zcmop_zihintpause_mazicsr_zba_zbb_zbc_zcb_zihintntl_zimop_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1
  -D RVE_E_ZBS=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_M=1
  -D RVE_E_A=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZIMOP=1
  -D RVE_E_MISALIGNED=1

[env:RV32ICZicsr_Zba_Zihintntl_MZaamo_Zalrsc_Zifencei_Zbb_Zbc_Zbkb_Zbkx_Zbs_Zcb_Zicond_Zihintpause_Zimop]
# act-config: rve-rv32iczicsr_zba_zihintntl_mzaamo_zalrsc_zifencei_zbb_zbc_zbkb_zbkx_zbs_zcb_zicond_zihintpause_zimop
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_M=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZBKB=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZBS=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_ZIMOP=1

[env:RV32ICZicsr_Zba_Zihintntl_Zaamo_Zalrsc_Zmmul_Zifencei_Zbb_Zbc_Zbkb_Zbkx_Zbs_Zcb_Zicntr_Zicond_Zihintpause_Misalign]
# act-config: rve-rv32iczicsr_zba_zihintntl_zaamo_zalrsc_zmmul_zifencei_zbb_zbc_zbkb_zbkx_zbs_zcb_zicntr_zicond_zihintpause_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZBKB=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZBS=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_MISALIGNED=1

[env:RV32ICZicsr_Zbb_Zimop_MAZifencei_Zba_Zbc_Zbkx_Zcb_Zcmop_Zicntr_Zihintpause_Misalign]
# act-config: rve-rv32iczicsr_zbb_zimop_mazifencei_zba_zbc_zbkx_zcb_zcmop_zicntr_zihintpause_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZIMOP=1
  -D RVE_E_M=1
  -D RVE_E_A=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_MISALIGNED=1

[env:RV32ICZifencei_Zihintpause_Misalign_MABZicsr_Zcb_Zcmop_Zicntr_Zihintntl]
# act-config: rve-rv32iczifencei_zihintpause_misalign_mabzicsr_zcb_zcmop_zicntr_zihintntl
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_C=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_MISALIGNED=1
  -D RVE_E_M=1
  -D RVE_E_A=1
  -D RVE_E_B=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZIHINTNTL=1

[env:RV32IMAZihintntl_Zimop_CBZifencei_Zcb_Zicond_Zihintpause_Misalign]
# act-config: rve-rv32imazihintntl_zimop_cbzifencei_zcb_zicond_zihintpause_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_M=1
  -D RVE_E_A=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZIMOP=1
  -D RVE_E_C=1
  -D RVE_E_B=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_MISALIGNED=1

[env:RV32IMCZicond_Zimop_BZaamo_Zalrsc_Zifencei_Zcmop_Zihintpause_Misalign]
# act-config: rve-rv32imczicond_zimop_bzaamo_zalrsc_zifencei_zcmop_zihintpause_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_M=1
  -D RVE_E_C=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIMOP=1
  -D RVE_E_B=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_MISALIGNED=1

[env:RV32IZaamo_Zmmul_Zicsr_Zbb_CZalrsc_Zba_Zbc_Zbkx_Zbs_Zcb_Zcmop_Zicntr_Zicond_Zimop]
# act-config: rve-rv32izaamo_zmmul_zicsr_zbb_czalrsc_zba_zbc_zbkx_zbs_zcb_zcmop_zicntr_zicond_zimop
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZBB=1
  -D RVE_E_C=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZBS=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIMOP=1

[env:RV32IZalrsc_Zifencei_Zihintntl_Zimop_MCBZaamo_Zicsr_Zcb_Zcmop_Zicond_Misalign]
# act-config: rve-rv32izalrsc_zifencei_zihintntl_zimop_mcbzaamo_zicsr_zcb_zcmop_zicond_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZIMOP=1
  -D RVE_E_M=1
  -D RVE_E_C=1
  -D RVE_E_B=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZICOND=1
  -D RVE_E_MISALIGNED=1

[env:RV32IZba_Zbkb_Zbkx_Zbs_MACZifencei_Zbb_Zbc_Zcb_Zcmop_Zicond_Zihintpause_Zimop]
# act-config: rve-rv32izba_zbkb_zbkx_zbs_maczifencei_zbb_zbc_zcb_zcmop_zicond_zihintpause_zimop
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZBA=1
  -D RVE_E_ZBKB=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZBS=1
  -D RVE_E_M=1
  -D RVE_E_A=1
  -D RVE_E_C=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_ZIMOP=1

[env:RV32IZicsr_Zbb_Zbkb_Zicond_ACZmmul_Zbkc_Zbkx_Zcb_Zcmop_Zihintntl_Misalign]
# act-config: rve-rv32izicsr_zbb_zbkb_zicond_aczmmul_zbkc_zbkx_zcb_zcmop_zihintntl_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZICSR=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBKB=1
  -D RVE_E_ZICOND=1
  -D RVE_E_A=1
  -D RVE_E_C=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZBKC=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_MISALIGNED=1

[env:RV32IZicsr_Zbkc_Zbs_Misalign_MACZifencei_Zba_Zbkb_Zbkx_Zcb_Zcmop_Zicntr_Zicond_Zihintntl_Zihintpause_Zimop]
# act-config: rve-rv32izicsr_zbkc_zbs_misalign_maczifencei_zba_zbkb_zbkx_zcb_zcmop_zicntr_zicond_zihintntl_zihintpause_zimop
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZICSR=1
  -D RVE_E_ZBKC=1
  -D RVE_E_ZBS=1
  -D RVE_E_MISALIGNED=1
  -D RVE_E_M=1
  -D RVE_E_A=1
  -D RVE_E_C=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBKB=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_ZIMOP=1

[env:RV32IZicsr_Zbkc_Zcb_Zcmop_MCZaamo_Zalrsc_Zifencei_Zba_Zbb_Zbkb_Zbs_Zicntr_Zihintpause_Misalign]
# act-config: rve-rv32izicsr_zbkc_zcb_zcmop_mczaamo_zalrsc_zifencei_zba_zbb_zbkb_zbs_zicntr_zihintpause_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZICSR=1
  -D RVE_E_ZBKC=1
  -D RVE_E_ZCB=1
  -D RVE_E_C=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_M=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBKB=1
  -D RVE_E_ZBS=1
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_MISALIGNED=1

[env:RV32IZifencei_Zbb_Zicond_Zimop_MZaamo_Zalrsc_Zicsr_Zba_Zbkc_Zbkb_Zbkx_Zbs_Zihintntl_Zihintpause_Misalign]
# act-config: rve-rv32izifencei_zbb_zicond_zimop_mzaamo_zalrsc_zicsr_zba_zbkc_zbkb_zbkx_zbs_zihintntl_zihintpause_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIMOP=1
  -D RVE_E_M=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBKC=1
  -D RVE_E_ZBKB=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZBS=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_MISALIGNED=1

[env:RV32IZifencei_Zbb_Zihintntl_Misalign_MCZaamo_Zalrsc_Zba_Zbc_Zbkb_Zbkx_Zcb_Zcmop_Zicond_Zihintpause_Zimop]
# act-config: rve-rv32izifencei_zbb_zihintntl_misalign_mczaamo_zalrsc_zba_zbc_zbkb_zbkx_zcb_zcmop_zicond_zihintpause_zimop
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_MISALIGNED=1
  -D RVE_E_M=1
  -D RVE_E_C=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBC=1
  -D RVE_E_ZBKB=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZCB=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_ZIMOP=1

[env:RV32IZifencei_Zbkc_Zicond_Zimop_CZaamo_Zalrsc_Zmmul_Zicsr_Zbb_Zbkx_Zcmop_Zicntr_Zihintntl_Zihintpause_Misalign]
# act-config: rve-rv32izifencei_zbkc_zicond_zimop_czaamo_zalrsc_zmmul_zicsr_zbb_zbkx_zcmop_zicntr_zihintntl_zihintpause_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZBKC=1
  -D RVE_E_ZICOND=1
  -D RVE_E_ZIMOP=1
  -D RVE_E_C=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_MISALIGNED=1

[env:RV32IZmmul_Zbb_Zbkc_Zbkb_CZaamo_Zalrsc_Zicsr_Zba_Zbkx_Zbs_Zcmop_Zicntr_Zihintntl_Zihintpause_Zimop_Misalign]
# act-config: rve-rv32izmmul_zbb_zbkc_zbkb_czaamo_zalrsc_zicsr_zba_zbkx_zbs_zcmop_zicntr_zihintntl_zihintpause_zimop_misalign
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZBB=1
  -D RVE_E_ZBKC=1
  -D RVE_E_ZBKB=1
  -D RVE_E_C=1
  -D RVE_E_ZAAMO=1
  -D RVE_E_ZALRSC=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZBA=1
  -D RVE_E_ZBKX=1
  -D RVE_E_ZBS=1
  -D RVE_E_ZCMOP=1
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_ZIMOP=1
  -D RVE_E_MISALIGNED=1

[env:RV32IZmmul_Zicsr_Zicond_Misalign_ABZifencei_Zicntr_Zihintntl_Zihintpause_Zimop]
# act-config: rve-rv32izmmul_zicsr_zicond_misalign_abzifencei_zicntr_zihintntl_zihintpause_zimop
# smoke
extends           = common
build_flags       =
  ${common.build_flags}
  -D RVE_E_ZMMUL=1
  -D RVE_E_ZICSR=1
  -D RVE_E_ZICOND=1
  -D RVE_E_MISALIGNED=1
  -D RVE_E_A=1
  -D RVE_E_B=1
  -D RVE_E_ZIFENCEI=1
  -D RVE_E_ZICNTR=1
  -D RVE_E_ZIHINTNTL=1
  -D RVE_E_ZIHINTPAUSE=1
  -D RVE_E_ZIMOP=1

